server:
  port: 9920
spring:
  application:
    name: bloggerservice
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka